/**
 * Created by Igor on 03.11.2016.
 */
const ADD_TODO    = 'ADD_TODO',
      TOGGLE_TODO = 'TOGGLE_TODO',
      DEL_TODO = 'DEL_TODO',
      FETCH_TODO_ALL = 'FETCH_TODO_ALL',
      FETCH_TODO_DONE = 'FETCH_TODO_DONE',
      FETCH_TODO_UNDONE = 'FETCH_TODO_UNDONE';

export {ADD_TODO, TOGGLE_TODO, DEL_TODO, FETCH_TODO_ALL, FETCH_TODO_DONE, FETCH_TODO_UNDONE}

